In [141]:
import pandas as pd
import numpy as np

from pandas import ExcelWriter
from pandas import ExcelFile

### Loading data

In [142]:
credit_clients_file = pd.read_excel('credit_clients.xls')
credit_clients_file.head()

Unnamed: 0         X1   X2         X3        X4   X5     X6     X7     X8  \
0         ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3   
1          1      20000    2          2         1   24      2      2     -1   
2          2     120000    2          2         2   26     -1      2      0   
3          3      90000    2          2         2   34      0      0      0   
4          4      50000    2          2         1   37      0      0      0   

      X9  ...        X15        X16        X17       X18       X19       X20  \
0  PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3   
1     -1  ...          0          0          0         0       689         0   
2      0  ...       3272       3455       3261         0      1000      1000   
3      0  ...      14331      14948      15549      1518      1500      1000   
4      0  ...      28314      28959      29547      2000      2019      1200   

        X21       X22       X23                           Y  
0  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
1         0         0         0                           1  
2      1000         0      2000                           1  
3      1000      1000      5000                           0  
4      1100      1069      1000                           0  

[5 rows x 25 columns]

In [143]:
class DataSet:
    def __init__(self, data = None, target = None):
        self.data = data
        self.target = target

In [144]:
clients_data = credit_clients_file.iloc[1:,1:-1]
clients_target = credit_clients_file.iloc[1:,-1]

clients_data.head(20)

X1 X2 X3 X4  X5  X6  X7  X8  X9 X10  ...     X14     X15     X16  \
1    20000  2  2  1  24   2   2  -1  -1  -2  ...     689       0       0   
2   120000  2  2  2  26  -1   2   0   0   0  ...    2682    3272    3455   
3    90000  2  2  2  34   0   0   0   0   0  ...   13559   14331   14948   
4    50000  2  2  1  37   0   0   0   0   0  ...   49291   28314   28959   
5    50000  1  2  1  57  -1   0  -1   0   0  ...   35835   20940   19146   
6    50000  1  1  2  37   0   0   0   0   0  ...   57608   19394   19619   
7   500000  1  1  2  29   0   0   0   0   0  ...  445007  542653  483003   
8   100000  2  2  2  23   0  -1  -1   0   0  ...     601     221    -159   
9   140000  2  3  1  28   0   0   2   0   0  ...   12108   12211   11793   
10   20000  1  3  2  35  -2  -2  -2  -2  -1  ...       0       0   13007   
11  200000  2  3  2  34   0   0   2   0   0  ...    5535    2513    1828   
12  260000  2  1  2  51  -1  -1  -1  -1  -1  ...    9966    8517   22287   
13  630000  2  2  2  41  -1   0  -1  -1  -1  ...    6500    6500    6500   
14   70000  1  2  2  30   1   2   2   0   0  ...   65701   66782   36137   
15  250000  1  1  2  29   0   0   0   0   0  ...   63561   59696   56875   
16   50000  2  3  3  23   1   2   0   0   0  ...   28116   28771   29531   
17   20000  1  1  2  24   0   0   2   2   2  ...   17428   18338   17905   
18  320000  1  1  1  49   0   0   0  -1  -1  ...  194663   70074    5856   
19  360000  2  1  1  49   1  -2  -2  -2  -2  ...       0       0       0   
20  180000  2  1  2  29   1  -2  -2  -2  -2  ...       0       0       0   

       X17    X18    X19    X20    X21     X22    X23  
1        0      0    689      0      0       0      0  
2     3261      0   1000   1000   1000       0   2000  
3    15549   1518   1500   1000   1000    1000   5000  
4    29547   2000   2019   1200   1100    1069   1000  
5    19131   2000  36681  10000   9000     689    679  
6    20024   2500   1815    657   1000    1000    800  
7   473944  55000  40000  38000  20239   13750  13770  
8      567    380    601      0    581    1687   1542  
9     3719   3329      0    432   1000    1000   1000  
10   13912      0      0      0  13007    1122      0  
11    3731   2306     12     50    300    3738     66  
12   13668  21818   9966   8583  22301       0   3640  
13    2870   1000   6500   6500   6500    2870      0  
14   36894   3200      0   3000   3000    1500      0  
15   55512   3000   3000   3000   3000    3000   3000  
16   30211      0   1500   1100   1200    1300   1100  
17   19104   3200      0   1500      0    1650      0  
18  195599  10358  10000  75940  20000  195599  50000  
19       0      0      0      0      0       0      0  
20       0      0      0      0      0       0      0  

[20 rows x 23 columns]

In [145]:
credit_clients = DataSet(np.array(clients_data, dtype=np.int32), np.array(clients_target, dtype=np.int32))

print(type(credit_clients.data))
print(type(credit_clients.target))

print(credit_clients.data.shape)
print(credit_clients.target.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(30000, 23)
(30000,)


In [146]:
print("First customer in database before scaling")
print(credit_clients.data[0])
print("Should have credit?")
print(credit_clients.target[0])

First customer in database before scaling
[20000     2     2     1    24     2     2    -1    -1    -2    -2  3913
  3102   689     0     0     0     0   689     0     0     0     0]
Should have credit?
1


In [147]:
print("---Mean---")
print(credit_clients.data.mean(axis=0))
print("---std---")
print(credit_clients.data.std(axis=0))

---Mean---
[ 1.67484323e+05  1.60373333e+00  1.85313333e+00  1.55186667e+00
  3.54855000e+01 -1.67000000e-02 -1.33766667e-01 -1.66200000e-01
 -2.20666667e-01 -2.66200000e-01 -2.91100000e-01  5.12233309e+04
  4.91790752e+04  4.70131548e+04  4.32629490e+04  4.03114010e+04
  3.88717604e+04  5.66358050e+03  5.92116350e+03  5.22568150e+03
  4.82607687e+03  4.79938763e+03  5.21550257e+03]
---std---
[1.29745499e+05 4.89121044e-01 7.90335487e-01 5.21960901e-01
 9.21775044e+00 1.12378280e+00 1.19716602e+00 1.19684762e+00
 1.16911914e+00 1.13316852e+00 1.14996846e+00 7.36346333e+04
 7.11725825e+04 6.93482316e+04 6.43317839e+04 6.07961425e+04
 5.95531150e+04 1.65630043e+04 2.30404864e+04 1.76066680e+04
 1.56658986e+04 1.52780510e+04 1.77771695e+04]


## Scaling data with StandardScaler

In [148]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

scaled_credit_clients = DataSet(scaler.fit_transform(credit_clients.data), credit_clients.target)

In [149]:
print("First client in database after scaling")
print(scaled_credit_clients.data[1])
print('---Mean---')
print(scaled_credit_clients.data.mean(axis=0))
print('--std---')
print(scaled_credit_clients.data.std(axis=0))

First client in database after scaling
[-0.3659805   0.81016074  0.18582826  0.85855728 -1.02904717 -0.87499115
  1.78234817  0.1388648   0.18874609  0.23491652  1.99231551 -0.65921875
 -0.66674657 -0.63925429 -0.62163594 -0.60622927 -0.59796638 -0.34194162
 -0.21358766 -0.24000461 -0.24422965 -0.31413612 -0.18087821]
---Mean---
[-6.06329801e-17  2.33058017e-16  6.25277607e-17 -7.57912251e-18
 -1.85688502e-16 -1.89478063e-17  4.92642963e-17 -5.49486382e-17
  3.12638804e-17 -3.03164901e-17  4.54747351e-17 -1.23160741e-17
 -3.78956126e-17  6.25277607e-17  5.87381995e-17 -2.36847579e-17
  1.13686838e-17 -4.73695157e-18  1.37371596e-17  2.08425869e-17
  1.80004160e-17 -1.96583490e-17 -1.78819922e-17]
--std---
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Split data in train and test batches

In [150]:
from sklearn.model_selection import train_test_split

clients_train_set = DataSet()
clients_test_set = DataSet()

clients_train_set.data, clients_test_set.data, \
clients_train_set.target, clients_test_set.target = \
train_test_split(scaled_credit_clients.data, scaled_credit_clients.target, test_size=0.1)


In [151]:
print("Training dataset:")
print("clients_train_set.data:", clients_train_set.data.shape)
print("clients_train_set.target:", clients_train_set.target.shape)

Training dataset:
clients_train_set.data: (27000, 23)
clients_train_set.target: (27000,)


In [152]:
print("Testing dataset:")
print("clients_test_set.data:", clients_test_set.data.shape)
print("clients_test_set.target:", clients_test_set.target.shape)

Testing dataset:
clients_test_set.data: (3000, 23)
clients_test_set.target: (3000,)


### Initiate and train model on training data

In [153]:
from sklearn.linear_model import LogisticRegression

credit_clients_logistic = LogisticRegression()
credit_clients_logistic.fit(clients_train_set.data, clients_train_set.target)

LogisticRegression()

### Using classifier

In [154]:
id = 2
credit_prediction = credit_clients_logistic.predict(clients_test_set.data[id,:].reshape(1,-1))
print("Model predicted for client {0} value {1}".format(id+1, credit_prediction))

print("Real value for client \"{0}\" is {1}".format(id+1, clients_test_set.target[id]))

Model predicted for client 3 value [0]
Real value for client "3" is 0


In [155]:
credit_prediction_probability = credit_clients_logistic.predict_proba(clients_test_set.data[id,:].reshape(1,-1))
print(credit_prediction_probability)

[[0.86266359 0.13733641]]


### Evaluate a classifier using the test data

In [156]:
from sklearn.metrics import accuracy_score

credit_acc = accuracy_score(clients_test_set.target, credit_clients_logistic.predict(clients_test_set.data))
print("Model accuracy is {0:0.5f}".format(credit_acc))

Model accuracy is 0.80167


### Evaluating classifier using confusion matrix

In [157]:
from sklearn.metrics import confusion_matrix

credit_conf_matrix = confusion_matrix(clients_test_set.target, credit_clients_logistic.predict(clients_test_set.data))
print(credit_conf_matrix)

[[2239   66]
 [ 529  166]]


In [158]:
tekst = "Evaluating classifier using confusion matrix"

print(tekst.upper())

EVALUATING CLASSIFIER USING CONFUSION MATRIX
